In [1]:
from sklearn.datasets import load_wine
import pandas as pd

In [2]:
# 1. 加载原始数据对象
wine = load_wine()

# 2. 将数值矩阵 (X) 转为 DataFrame，并贴上对应的特征标签
df = pd.DataFrame(wine.data, columns=wine.feature_names)

# 3. 将分类结果 (y) 作为一个新列加入表格
df['target'] = wine.target

In [3]:
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

Use wine dataset from sklearn.datasets to classify wines into 3 categories. Load the dataset and split it into test and train. After that train the model using Gaussian and Multinominal classifier and post which model performs better. Use the trained model to perform some predictions on test data.

In [4]:
df.groupby('target').size()

target
0    59
1    71
2    48
dtype: int64

In [5]:
df1 = df[['alcohol', 'malic_acid', 'color_intensity', 'od280/od315_of_diluted_wines','target']]
df1.head()

   alcohol  malic_acid  color_intensity  od280/od315_of_diluted_wines  target
0    14.23        1.71             5.64                          3.92       0
1    13.20        1.78             4.38                          3.40       0
2    13.16        2.36             5.68                          3.17       0
3    14.37        1.95             7.80                          3.45       0
4    13.24        2.59             4.32                          2.93       0

In [6]:
inputs = df1.drop('target', axis=1)
target = df1['target']
inputs.head(3)

   alcohol  malic_acid  color_intensity  od280/od315_of_diluted_wines
0    14.23        1.71             5.64                          3.92
1    13.20        1.78             4.38                          3.40
2    13.16        2.36             5.68                          3.17

In [7]:
inputs.columns[inputs.isna().any()]

Index([], dtype='object')

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.3)

In [9]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [10]:
model.fit(X_train, y_train)

GaussianNB()

In [11]:
model.score(X_test, y_test)

0.9629629629629629

In [12]:
X_test[:10]

     alcohol  malic_acid  color_intensity  od280/od315_of_diluted_wines
142    13.52        3.17             4.35                          2.06
22     13.71        1.86             3.80                          4.00
158    14.34        1.68            13.00                          1.96
8      14.83        1.64             5.20                          2.85
153    13.23        3.30            10.52                          1.51
54     13.74        1.67             5.85                          3.20
1      13.20        1.78             4.38                          3.40
16     14.30        1.92             6.20                          2.65
111    12.52        2.43             2.00                          2.78
70     12.29        1.61             3.05                          1.82

In [13]:
y_test[:10]

142    2
22     0
158    2
8      0
153    2
54     0
1      0
16     0
111    1
70     1
Name: target, dtype: int64

In [14]:
model.predict(X_test[:10])

array([2, 0, 2, 0, 2, 0, 0, 0, 1, 1])

In [15]:
model.predict_proba(X_test[:10])

array([[1.20602291e-02, 1.05647645e-01, 8.82292126e-01],
       [9.48583756e-01, 5.14162442e-02, 8.66666250e-17],
       [1.17109198e-05, 8.68069202e-23, 9.99988289e-01],
       [9.99886164e-01, 1.13233265e-04, 6.02573725e-07],
       [7.48753063e-09, 2.57414855e-15, 9.99999993e-01],
       [9.99689128e-01, 3.10866563e-04, 5.04501610e-09],
       [8.77486242e-01, 1.22513758e-01, 2.23484305e-10],
       [9.99843869e-01, 5.84287470e-05, 9.77017893e-05],
       [8.98022288e-04, 9.99099574e-01, 2.40354302e-06],
       [1.21510094e-06, 9.85398988e-01, 1.45997970e-02]])

In [16]:
from sklearn.naive_bayes import MultinomialNB
model2 = MultinomialNB()
model2.fit(X_train, y_train)

MultinomialNB()

In [17]:
model2.score(X_test, y_test)

0.7592592592592593

In [18]:
model2.predict(X_test[:10])

array([1, 1, 2, 1, 2, 0, 1, 0, 1, 1])

In [19]:
model2.predict_proba(X_test[:10])

array([[0.31103145, 0.43477026, 0.2541983 ],
       [0.35583763, 0.60510216, 0.03906021],
       [0.34438233, 0.01592238, 0.63969529],
       [0.44325175, 0.44958785, 0.1071604 ],
       [0.19979482, 0.02497809, 0.77522709],
       [0.50833327, 0.36970105, 0.12196568],
       [0.4132091 , 0.51321245, 0.07357845],
       [0.48463392, 0.32417032, 0.19119576],
       [0.23495684, 0.70624757, 0.05879559],
       [0.32482971, 0.55358047, 0.12158982]])

In [20]:
df[['color_intensity', 'hue']].corr()

                 color_intensity       hue
color_intensity         1.000000 -0.521813
hue                    -0.521813  1.000000

In [21]:
df.corr()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
alcohol,1.000000,0.094397,0.211545,-0.310235,0.270798,0.289101,0.236815,-0.155929,0.136698,0.546364,-0.071747,0.072343,0.643720,-0.328222
malic_acid,0.094397,1.000000,0.164045,0.288500,-0.054575,-0.335167,-0.411007,0.292977,-0.220746,0.248985,-0.561296,-0.368710,-0.192011,0.437776
ash,0.211545,0.164045,1.000000,0.443367,0.286587,0.128980,0.115077,0.186230,0.009652,0.258887,-0.074667,0.003911,0.223626,-0.049643
alcalinity_of_ash,-0.310235,0.288500,0.443367,1.000000,-0.083333,-0.321113,-0.351370,0.361922,-0.197327,0.018732,-0.273955,-0.276769,-0.440597,0.517859
magnesium,0.270798,-0.054575,0.286587,-0.083333,1.000000,0.214401,0.195784,-0.256294,0.236441,0.199950,0.055398,0.066004,0.393351,-0.209179
total_phenols,0.289101,-0.335167,0.128980,-0.321113,0.214401,1.000000,0.864564,-0.449935,0.612413,-0.055136,0.433681,0.699949,0.498115,-0.719163
flavanoids,0.236815,-0.411007,0.115077,-0.351370,0.195784,0.864564,1.000000,-0.537900,0.652692,-0.172379,0.543479,0.787194,0.494193,-0.847498
nonflavanoid_phenols,-0.155929,0.292977,0.186230,0.361922,-0.256294,-0.449935,-0.537900,1.000000,-0.365845,0.139057,-0.262640,-0.503270,-0.311385,0.489109
proanthocyanins,0.136698,-0.220746,0.009652,-0.197327,0.236441,0.612413,0.652692,-0.365845,1.000000,-0.025250,0.295544,0.519067,0.330417,-0.499130
color_intensity,0.546364,0.248985,0.258887,0.018732,0.199950,-0.055136,-0.172379,0.139057,-0.025250,1.000000,-0.521813,-0.428815,0.316100,0.265668
hue,-0.071747,-0.561296,-0.074667,-0.273955,0.055398,0.433681,0.543479,-0.262640,0.295544,-0.521813,1.000000,0.565468,0.236183,-0.617369
od280/od315_of_diluted_wines,0.072343,-0.368710,0.003911,-0.276769,0.066004,0.699949,0.787194,-0.503270,0.519067,-0.428815,0.565468,1.000000,0.312761,-0.788230
proline,0.643720,-0.192011,0.223626,-0.440597,0.393351,0.498115,0.494193,-0.311385,0.330417,0.316100,0.236183,0.312761,1.000000,-0.633717
target,-0.328222,0.437776,-0.049643,0.517859,-0.209179,-0.719163,-0.847498,0.489109,-0.499130,0.265668,-0.617369,-0.788230,-0.633717,1.000000

In [22]:
df[['total_phenols', 'od280/od315_of_diluted_wines']].corr()

                              total_phenols  od280/od315_of_diluted_wines
total_phenols                      1.000000                      0.699949
od280/od315_of_diluted_wines       0.699949                      1.000000

In [23]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.96 , 0.84 , 0.92 , 0.96 , 0.875])